### ISSUE TITLE
Weird stdout output when using the value 'Name' for the property name

### ISSUE THREAD

**Issue by fstj** [G-Node/odml-java-lib#4]
I'm using the java odML library in matlab and I get the following output in the MATLAB console when a property in the odML file is named 'Name':
```
Section.setName: provided name is in conflict with the one provided by the 'name' property! No change done!
Section.addProperty: New Property overrides the section name. Section name was replaced!
```

You can generate this output for example by runnning the MATLAB function odml2struct on the following odML file:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet  type="text/xsl" href="odmlTerms.xsl"?>
<?xml-stylesheet  type="text/xsl" href="odml.xsl"?>
<odML version="1">
  <section>
    <name>test</name>
    <property>
      <value>a_nice_name<type>string</type></value>
      <name>Name</name>
    </property>
    <type>test_section</type>
  </section>
</odML>
```
The resulting struct returned in MATLAB seems correct, containing a property named 'Name' as expected. So the java library seems to work as it should, but it is ouputing this uneeded weird message.

In the odML file, if I replace the value 'Name' by an other name (for example 'ame'), I don't get the weird output anymore.

Would it be possible to modify the java library to avoid having the unneeded message when the name of the property is 'Name'?

**Comment by jgrewe** [comment]
Hm, this is mostly intended behavior. The additional Property in fact redefines the name with something else. The message warns 
Is this a feature you need? I mean, do you require different names in the section and the additional name property?
 
A message like this was  always there but it is merely a warning and did not make it to the std out. With the last changes in the java lib, they became visible. 

Best,
Jan

**Comment by lzehl** [comment]
I'm not sure if this is intended behaviour. In general, attributes of a property should not overwrite the section attributes, therefore the attribute 'name' of the property should be independent from the attritbute 'name' of the section. So it should not be a problem to add a property called 'Name' to a section called 'test'. This is at least how I understood the issue. One could of course work around this warning and call the property something else/more than 'Name', but I'm not sure if this is a nice solution. Let me know what you think. 

Best, Lyuba

**Comment by jgrewe** [comment]
Let me put it differently. When you find a section with the name "XYZ" how would you interpret the containing property "Name" setting it to "Something else"? In my view this provides ambiguous information.
If you really need this I would rather keep the warning but  allow it .

**Comment by lzehl** [comment]
I see your point. But let me give an example where it is not really ambiguous: imagine a Section called 'Experimenter'. This Section contains Properties describing the 'Experimenter' e.g. 'Name', 'Email', 'Affilitation'...
But I agree, there are not many cases where this occurs and it is not ambiguous. And even in the case above one could work around using 'FirstName' and 'LastName'. 
The warning is not produced using the python-odml library. That's why I was surprised.

**Comment by jgrewe** [comment]
Fair enough, you can consider me convinced.

**Comment by jgrewe** [comment]
Done! Changed the respective parts.
