### ISSUE TITLE
Annoying message when accessing undefined reference for a value

### ISSUE THREAD

**Issue by fstj** [G-Node/odml-java-lib#5]
When trying to read the reference for a value in a property, and this reference is not defined in the odML file, the following message is printed to stdout:
```
! no id stored for given value specified by its index!
```

This is due to the following code in the method getValueReference of odml-java-lib/src/odml/core/Property.java:
```
if (reference != null && reference.isEmpty()) {
   System.out.println("! no id stored for given value specified by its index!");
   return null;
}
```

Having this message displayed can be annoying in certain cases, and there doesn't seem to be any way to force this message to not be displayed.

In my case, I'm using the odml2struct function in MATLAB to read a very big odML file in which no references are specified. As odml2struct is a generic function, it tries to access every possible attributes of the value, even if they are not defined in the odML file, so I end up having the message displayed for each of the value in my file, which means some thousands of times for my very big file. This slows down significantly the reading process and prevents me from seeing the other warning messages that could be printed during reading.

This problem is only happening for the reference attribute of a value. When trying to read other optional attributes that are not defined in the odML file, no message is displayed, which is good in my point of view. 

Would it be possible to remove the message or to give an option when calling getValueReference to have the message not displayed to avoid the problem?

**Comment by jgrewe** [comment]
I guess this message can go. You're receiving a null element anyways. Did you experience other messages like this?

**Comment by jgrewe** [comment]
solved with latest commit

**Comment by fstj** [comment]
No, I didn't experience other messages like this.
Thanks for the fix.

**Comment by jgrewe** [comment]
Thanks for the reply. Removed more of such info-style messages. There will be std out messages when things go wrong, though. Let me know if there are other problems etc....
